# api version - scopes limits the types of objects that we can specify
apiVersion: v1
#kind = object type: StatefulSet, ReplicaController, Pod, Service
# service = setup networking
# pod = object to run a container


#The port(3050) means that client-node-port can be accessed by other services in the cluster on port 3050

#The targetPort(8080) means that the client-node-port is actually running on port 8080 on pods

#The nodePort(31515) means that client-node-port can be accessed via kube-proxy on port 31515

kind: Service  
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 8080
      nodePort: 31515
  selector:
    component: web
